apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-eventarc
spec:
  compositeTypeRef:
    apiVersion: eventarc.example.com/v1alpha1
    kind: XGCPEventArc
  resources:
    - name: eventarc-triggers
      base:
        apiVersion: eventarc.gcp.crossplane.io/v1beta1
        kind: Trigger
        spec:
          forProvider:
            eventFilters:
              - attribute: "type"
                value: "apigee.request"
            transport:
              pubsub:
                topic: "{{ .Values.eventarc.triggers[0].topic }}"
            destination:
              cloudRun:
                service: "{{ .Values.eventarc.triggers[0].destinationService }}"
                region: "{{ .Values.eventarc.region }}"
          providerConfigRef:
            name: "{{ .Values.eventarc.providerConfig }}"
      patches:
        - fromFieldPath: "spec.triggers[0].name"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.triggers[0].topic"
          toFieldPath: "spec.forProvider.transport.pubsub.topic"
        - fromFieldPath: "spec.triggers[0].destinationService"
          toFieldPath: "spec.forProvider.destination.cloudRun.service"
