kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: crossplane-ha-control-plane
networking:
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  # Control Plane Nodes
  - role: control-plane
    image: kindest/node:v1.31.0
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6443
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
  - role: control-plane
    image: kindest/node:v1.31.0
  - role: control-plane
    image: kindest/node:v1.31.0

  # Worker Nodes
  - role: worker
    image: kindest/node:v1.31.0
  - role: worker
    image: kindest/node:v1.31.0
  - role: worker
    image: kindest/node:v1.31.0
