apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: minimal-gke-cluster
spec:
  forProvider:
    location: us-west4-a
    initialClusterVersion: "1.31"
    
    # In v1beta2, node configuration is not directly in nodeConfig
    # Instead, we need to create a nodePool with the configuration
    defaultMaxPodsConstraint:
      maxPodsPerNode: 110
    
    # We need to add nodePools in a different way now
    addonsConfig:
      httpLoadBalancing:
        disabled: false
      horizontalPodAutoscaling:
        disabled: false
    
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
    
    # Added master auth configuration to null out credentials
    masterAuth:
      clientCertificateConfig:
        issueClientCertificate: false
  
  providerConfigRef:
    name: default
  
  writeConnectionSecretToRef:
    namespace: default
    name: gke-creds