apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgcpapigee.enginevector.io
spec:
  group: apigee.enginevector.io
  names:
    kind: XGCPApigee
    plural: xgcpapigees
  claimNames:
    kind: GCPApigeeClaim
    plural: gcpapigeeclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                region:
                  type: string
                gatewayName:
                  type: string
                privateLink:
                  type: boolean
              required:
                - projectId
                - region
                - gatewayName
