apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgcpappengine.enginevector.io  # Change to a template (add to values.yaml)
spec:
  group: appengine.enginevector.io     # Change to a template
  names:
    kind: XGCPAppEngine
    plural: xgcpappengines
  claimNames:
    kind: GCPAppEngineClaim
    plural: gcpappengineclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                appId:
                  type: string
                region:
                  type: string
              required:
                - projectId
                - appId
                - region
