argo-cd:
  global:
    domain: argocd.prod.eql.cloud
  
  redis-ha:
    enabled: true
    
  controller:
    replicas: 2
    
  server:
    replicas: 2
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - argocd.prod.eql.cloud
      tls:
        - secretName: argocd-server-tls
          hosts:
            - argocd.prod.eql.cloud
    
    config:
      url: https://argocd.prod.eql.cloud
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $github_oauth_client_id
              clientSecret: $github_oauth_client_secret
              orgs:
                - name: eql-org

  dex:
    enabled: true
    
  repoServer:
    replicas: 2
    
  applicationSet:
    enabled: true
    replicas: 2