apiVersion: v2
name: crossplane
description: Crossplane for EQL Cloud and Kubernetes Resource Management
version: 1.0.0
dependencies:
  - name: crossplane
    version: 1.14.1
    repository: https://charts.crossplane.io/stable