apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-cloudrun
spec:
  compositeTypeRef:
    apiVersion: cloudrun.example.com/v1alpha1
    kind: XGCPCloudRun
  resources:
    - name: cloud-run-service
      base:
        apiVersion: serving.knative.dev/v1
        kind: Service
        spec:
          template:
            spec:
              containers:
                - image: "gcr.io/my-project/my-app"
          providerConfigRef:
            name: gcp-provider
      patches:
        - fromFieldPath: "spec.serviceName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
