apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-spanner
spec:
  compositeTypeRef:
    apiVersion: databases.enginevector.io/v1alpha1
    kind: XGCPSpanner
  resources:
    - name: spanner-instance
      base:
        apiVersion: spanner.gcp.crossplane.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            config: "regional-{{ .Values.spanner.region }}"
            displayName: {{ .Values.spanner.instanceName }}
            nodeCount: {{ .Values.spanner.nodeCount }}
          providerConfigRef:
            name: {{ .Values.spanner.providerConfig }}
      patches:
        - fromFieldPath: "spec.instanceName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.config"
        - fromFieldPath: "spec.nodeCount"
          toFieldPath: "spec.forProvider.nodeCount"

    - name: helm-release-spanner
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: spanner-instance
        spec:
          forProvider:
            chart:
              name: gcp-databases
              repository: "https://github.com/isgo-golgo13/crossplane-argocd-gcp-drone-attack-services.git"
              version: "1.0.0"
            namespace: crossplane-system
            values:
              spanner:
                region: {{ .Values.spanner.region }}
                instanceName: {{ .Values.spanner.instanceName }}
                nodeCount: {{ .Values.spanner.nodeCount }}
                providerConfig: {{ .Values.spanner.providerConfig }}
          providerConfigRef:
            name: gcp-provider
