apiVersion: v2
name: cert-manager
description: Certificate Management for EQL clusters
version: 1.0.0
dependencies:
  - name: cert-manager
    version: v1.13.2
    repository: https://charts.jetstack.io