apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-gke
spec:
  compositeTypeRef:
    apiVersion: gke.enginevector.io/v1alpha1
    kind: XGCPGKE
  resources:
    - name: gke-cluster
      base:
        apiVersion: container.gcp.crossplane.io/v1beta1
        kind: Cluster
        spec:
          forProvider:
            location: {{ .Values.gke.region }}
            initialNodeCount: {{ .Values.gke.nodeCount }}
            networkRef:
              name: {{ .Values.gke.networkRef }}
          providerConfigRef:
            name: {{ .Values.gke.providerConfig }}
      patches:
        - fromFieldPath: "spec.clusterName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.location"
        - fromFieldPath: "spec.nodeCount"
          toFieldPath: "spec.forProvider.initialNodeCount"

    - name: gke-nodepool
      base:
        apiVersion: container.gcp.crossplane.io/v1beta1
        kind: NodePool
        spec:
          forProvider:
            clusterRef:
              name: {{ .Values.gke.clusterName }}
            locations:
              - {{ .Values.gke.region }}
            autoscaling:
              minNodeCount: {{ .Values.gke.nodePool.minNodeCount }}
              maxNodeCount: {{ .Values.gke.nodePool.maxNodeCount }}
            management:
              autoRepair: {{ .Values.gke.nodePool.autoRepair }}
              autoUpgrade: {{ .Values.gke.nodePool.autoUpgrade }}
            config:
              machineType: {{ .Values.gke.nodePool.machineType }}
              diskSizeGb: {{ .Values.gke.nodePool.diskSizeGb }}
              diskType: {{ .Values.gke.nodePool.diskType }}
              labels: {{ .Values.gke.nodePool.labels }}
              taints: {{ .Values.gke.nodePool.taints }}
          providerConfigRef:
            name: {{ .Values.gke.providerConfig }}
      patches:
        - fromFieldPath: "spec.clusterName"
          toFieldPath: "spec.forProvider.clusterRef.name"

    - name: gke-helm-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          forProvider:
            chart:
              name: {{ .Values.gke.helm.chartPath }}
              repository: {{ .Values.gke.helm.repo }}
              version: {{ .Values.gke.helm.version }}
            namespace: {{ .Values.gke.helm.namespace }}
            values:
              projectId: {{ .Values.gke.helm.values.projectId }}
              clusterName: {{ .Values.gke.helm.values.clusterName }}
              region: {{ .Values.gke.helm.values.region }}
              nodeCount: {{ .Values.gke.helm.values.nodeCount }}
              networkRef: {{ .Values.gke.helm.values.networkRef }}
              providerConfig: {{ .Values.gke.helm.values.providerConfig }}
          providerConfigRef:
            name: {{ .Values.gke.providerConfig }}
