apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgcpspanner.example.com
spec:
  group: databases.example.com
  names:
    kind: XGCPSpanner
    plural: xgcpspanners
  claimNames:
    kind: GCPSpannerClaim
    plural: gcpspannerclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                instanceName:
                  type: string
                region:
                  type: string
                nodeCount:
                  type: integer
              required:
                - projectId
                - instanceName
                - region
