apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-spanner
spec:
  compositeTypeRef:
    apiVersion: databases.example.com/v1alpha1
    kind: XGCPSpanner
  resources:
    - name: spanner-instance
      base:
        apiVersion: spanner.gcp.crossplane.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            config: "regional-us-central1"
            displayName: "Spanner Instance"
            nodeCount: 3
          providerConfigRef:
            name: gcp-provider
      patches:
        - fromFieldPath: "spec.instanceName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.config"
        - fromFieldPath: "spec.nodeCount"
          toFieldPath: "spec.forProvider.nodeCount"
