apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-spanner
spec:
  compositeTypeRef:
    apiVersion: databases.enginevector.io/v1alpha1
    kind: XGCPSpanner
  resources:
    - name: spanner-instance
      base:
        apiVersion: spanner.gcp.crossplane.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            config: "regional-{{ .Values.spanner.region }}"
            displayName: {{ .Values.spanner.instanceName }}
            nodeCount: {{ .Values.spanner.nodeCount }}
          providerConfigRef:
            name: {{ .Values.spanner.providerConfig }}
      patches:
        - fromFieldPath: "spec.instanceName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.config"
        - fromFieldPath: "spec.nodeCount"
          toFieldPath: "spec.forProvider.nodeCount"
