apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-firestore
spec:
  compositeTypeRef:
    apiVersion: databases.example.com/v1alpha1
    kind: XGCPFirestore
  resources:
    - name: firestore-db
      base:
        apiVersion: firestore.gcp.crossplane.io/v1beta1
        kind: Database
        spec:
          forProvider:
            locationId: "us-central1"
            type: "FIRESTORE_NATIVE"
          providerConfigRef:
            name: gcp-provider
      patches:
        - fromFieldPath: "spec.databaseId"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.locationId"
