apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgcpfirestore.enginevector.io
spec:
  group: databases.enginevector.io
  names:
    kind: XGCPFirestore
    plural: xgcpfirestores
  claimNames:
    kind: GCPFirestoreClaim
    plural: gcpfirestoreclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                databaseId:
                  type: string
                region:
                  type: string
              required:
                - projectId
                - databaseId
                - region
