apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-crossplane-creds
  namespace: external-secrets
spec:
  refreshInterval: {{ .Values.eso.refreshInterval }}
  secretStoreRef:
    name: azure-workload-identity-store
    kind: ClusterSecretStore
  target:
    name: azure-crossplane-creds
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: azure-crossplane-creds
