apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-workload-identity-store
  namespace: external-secrets
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.azure.tenantId }}
      auth:
        workloadIdentity:
          clientID: {{ .Values.crossplane.serviceAccount }}
          resourceGroup: {{ .Values.azure.resourceGroup }}
