apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster Apps
  sourceRepos:
    - 'https://github.com/eql/*'
  destinations:
    - namespace: '*-*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: 'networking.k8s.io'
      kind: '*'