sealed-secrets:
  replicaCount: 3
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  metrics:
    serviceMonitor:
      enabled: false
  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true