projectId: "cp-gcp-drone-svcs-project"

gke:
  clusterName: "gke-cluster"
  region: "us-west4"
  nodeCount: 3
  networkRef: "shared-vpc"
  providerConfig: "gcp-provider"
  # nodePool:
  #   name: "default-node-pool"
  #   machineType: "n1-standard-1"
  #   diskSizeGb: 100
  #   diskType: "pd-standard"
  #   minNodeCount: 1
  #   maxNodeCount: 3
  #   autoRepair: true
  #   autoUpgrade: true
  #   labels:
  #     environment: "nonprod"
  #     team: "platform-engineering"
  #   taints:
  #     - key: "node-type"
  #       value: "infra"
  #       effect: "NO_SCHEDULE"