# docker-compose.frontend.yml
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./static:/app/static
    command: npm run dev -- --host=0.0.0.0
