apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgcpcloudstorage.enginevector.io
spec:
  group: cloudstorage.enginevector.io
  names:
    kind: XGCPCloudStorage
    plural: xgcpcloudstorages
  claimNames:
    kind: GCPCloudStorageClaim
    plural: gcpcloudstorageclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                bucketName:
                  type: string
                location:
                  type: string
                storageClass:
                  type: string
                versioning:
                  type: boolean
                publicAccessPrevention:
                  type: string
              required:
                - projectId
                - bucketName
                - location
                - storageClass
