gcp:
  projectId: "cxp-gcp"

crossplane:
  namespace: "crossplane-system"
  serviceAccount: "crossplane-sa"
  providerImage: "crossplane/provider-gcp:v0.22.0"
  replicas: 3
  enableCompositionRevisions: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
  leaderElection:
    enabled: true
  rbacManager:
    enabled: true
  securityContext:
    runAsNonRoot: true
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
  controllerConfigName: "crossplane-provider-controller-config"

eso:
  enabled: true
  refreshInterval: "1h"

argocd:
  enabled: true
  namespace: "argocd"
  insecure: true  
  tls:
    enabled: false  # Turn on later for Dex/SSO/TLS ingress
  ha:
    enabled: true
  applicationSet:
    enabled: true

externalSecrets:
  enabled: true
  namespace: "external-secrets"
  clusterSecretStoreName: "gcp-workload-identity-store"

certManager:
  enabled: true
  namespace: "cert-manager"
