gcp:
  projectId: "eql-hub"

crossplane:
  namespace: "crossplane-system"
  serviceAccount: "crossplane-sa"
  providerImage: "crossplane/provider-gcp:v0.22.0"
  controllerConfigName: "crossplane-provider-controller-config"
  replicas: 3
  enableCompositionRevisions: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
  leaderElection:
    enabled: true
  rbacManager:
    enabled: true
  securityContext:
    runAsNonRoot: true

eso:
  refreshInterval: "1h"

argocd:
  enabled: false
  namespace: "argocd"
  insecure: true  
  tls:
    enabled: false  # Turn on later for Dex/SSO/TLS ingress
  ha:
    enabled: true
  applicationSet:
    enabled: true

externalSecrets:
  namespace: "external-secrets"
  clusterSecretStoreName: "gcp-workload-identity-store"

certManager:
  namespace: "cert-manager"