gcp:
  projectId: "cxp-gcp"

crossplane:
  namespace: "crossplane-system"
  serviceAccount: "crossplane-sa"
  providerImage: "crossplane/provider-gcp:v0.22.0"
  replicas: 3
  enableCompositionRevisions: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
  leaderElection:
    enabled: true
  rbacManager:
    enabled: true
  securityContext:
    runAsNonRoot: true
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"

  controllerConfigName: "crossplane-provider-controller-config"

eso:
  enabled: true  # Toggle installation ON/OFF
  refreshInterval: "1h"

argocd:
  enabled: true  # Toggle installation ON/OFF
  namespace: "argocd"
  insecure: true  # Set to false when SSO/TLS is configured

externalSecrets:
  enabled: true  # Toggle installation ON/OFF
  namespace: "external-secrets"
  clusterSecretStoreName: "gcp-workload-identity-store"

certManager:
  enabled: true  # Toggle installation ON/OFF
  namespace: "cert-manager"

helm:
  dependencies:
    - name: crossplane
      version: "1.14.2"
      repository: "https://charts.crossplane.io/stable"
      values:
        args:
          - "--enable-composition-revisions"
        replicas: 3
        podDisruptionBudget:
          enabled: true
          minAvailable: 2
        leaderElection:
          enabled: true
        rbacManager:
          enabled: true
        securityContext:
          runAsNonRoot: true
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"