apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgkeclusters.gcp.platform.org
spec:
  group: gcp.platform.org
  names:
    kind: XGKECluster
    plural: xgkeclusters
  claimNames:
    kind: GCPGKECluster
    plural: gcpgkeclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    # GCP and VPC properties
                    projectId:
                      type: string
                      description: "GCP Project ID where the cluster will be created."
                    region:
                      type: string
                      description: "GCP region for the cluster (e.g., us-central1)."
                    zone:
                      type: string
                      description: "GCP zone for the cluster (e.g., us-central1-a)."
                    vpcNetwork:
                      type: string
                      description: "The name of the shared VPC network."
                    vpcSubnetwork:
                      type: string
                      description: "The name of the subnet within the shared VPC network."
                    
                    # Cluster properties
                    clusterName:
                      type: string
                      description: "The name of the GKE cluster."
                    kubernetesVersion:
                      type: string
                      description: "The version of Kubernetes to use for the cluster."
                      default: "latest"
                    privateCluster:
                      type: boolean
                      description: "Whether to create a private cluster."
                      default: true
                    enableWorkloadIdentity:
                      type: boolean
                      description: "Whether to enable GCP Workload Identity for the cluster."
                      default: true
                    
                    # Node pool properties
                    nodePools:
                      type: array
                      description: "Configuration for node pools in the cluster."
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: "The name of the node pool."
                          machineType:
                            type: string
                            description: "The GCP machine type for the nodes."
                          initialNodeCount:
                            type: integer
                            description: "The initial number of nodes in the pool."
                          minNodeCount:
                            type: integer
                            description: "Minimum number of nodes for autoscaling."
                          maxNodeCount:
                            type: integer
                            description: "Maximum number of nodes for autoscaling."
                          diskSizeGb:
                            type: integer
                            description: "Size of the disk attached to each node in GB."
                          diskType:
                            type: string
                            description: "Type of disk attached to each node."
                        required:
                          - name
                          - machineType
                    
                    # Add-ons configuration
                    addons:
                      type: object
                      properties:
                        certManager:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              default: true
                        kyverno:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              default: true
                        externalSecrets:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              default: true
                        prometheus:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              default: true
                  required:
                    - projectId
                    - region
                    - clusterName
              required:
                - parameters
            status:
              type: object
              properties:
                clusterName:
                  type: string
                  description: "The name of the provisioned GKE cluster."
                endpoint:
                  type: string
                  description: "The endpoint of the GKE cluster API server."
                kubeconfig:
                  type: string
                  description: "Base64-encoded kubeconfig for the GKE cluster."