apiVersion: v2
name: kyverno
description: Kyverno Kubernetes Policy Engine for EQL clusters
version: 1.0.0
dependencies:
  - name: kyverno
    version: 3.0.5
    repository: https://kyverno.github.io/kyverno