apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-workload-identity-store
  namespace: external-secrets
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId }}
      auth:
        workloadIdentity:
          clusterName: {{ .Values.gcp.clusterName }}
          clusterLocation: {{ .Values.gcp.clusterLocation }}
          serviceAccountRef:
            name: {{ .Values.crossplane.serviceAccount }}
            namespace: {{ .Values.crossplane.namespace }}