apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-provider-config
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  projectID: {{ .Values.gcp.projectId }}
  credentials:
    source: Secret
    secretRef:
      namespace: external-secrets
      name: gcp-crossplane-creds
      key: credentials.json