# templates/crossplane-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.crossplane.serviceAccount }}
  namespace: {{ .Values.crossplane.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.gsaEmail }}
