apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-crossplane-creds
  namespace: external-secrets
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: {{ .Values.eso.refreshInterval }}
  secretStoreRef:
    name: gcp-workload-identity-store
    kind: ClusterSecretStore
  target:
    name: gcp-crossplane-creds
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: gcp-crossplane-creds