apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-cloudrun
spec:
  compositeTypeRef:
    apiVersion: cloudrun.enginevector.io/v1alpha1
    kind: XGCPCloudRun
  resources:
    - name: cloud-run-service
      base:
        apiVersion: serving.knative.dev/v1
        kind: Service
        spec:
          template:
            spec:
              containers:
                - image: {{ .Values.cloudrun.image }}
          providerConfigRef:
            name: {{ .Values.cloudrun.providerConfig }}
      patches:
        - fromFieldPath: "spec.serviceName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"

    - name: helm-release-cloudrun
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: cloudrun-service
        spec:
          forProvider:
            chart:
              name: gcp-cloudrun
              repository: "https://github.com/isgo-golgo13/crossplane-argocd-gcp-drone-attack-services.git"
              version: "1.0.0"
            namespace: crossplane-system
            values:
              cloudrun:
                serviceName: {{ .Values.cloudrun.serviceName }}
                image: {{ .Values.cloudrun.image }}
                providerConfig: {{ .Values.cloudrun.providerConfig }}
                region: {{ .Values.cloudrun.region }}
          providerConfigRef:
            name: gcp-provider
