apiVersion: gcp.platform.eql.com/v1alpha1
kind: GCPGKECluster
metadata:
  name: eql-gcp-gke-cluster
  namespace: app-x
spec:
  parameters:
    projectId: eql-hub
    region: us-central1
    zone: us-central1-a
    vpcNetwork: shared-vpc-network
    vpcSubnetwork: shared-subnet

    clusterName: "eql-gcp-gke-private-cluster"
    kubernetesVersion: "1.31"
    privateCluster: true
    enableWorkloadIdentity: true

    nodePools:
      - name: main-pool
        machineType: e2-standard-8
        initialNodeCount: 2
        minNodeCount: 2
        maxNodeCount: 8
        diskSizeGb: 200
        diskType: pd-ssd

    addons:
      certManager:
        enabled: true
      kyverno:
        enabled: true
      externalSecrets:
        enabled: true
      prometheus:
        enabled: true

  compositionRef:
    name: gcp-private-gke-clusters
  writeConnectionSecretToRef:
    name: eql-gcp-gke-cluster-connection
    namespace: app-x