projectId: "cxp-gcp"

gke:
  clusterName: "gke-cluster"
  region: "us-west4"
  nodeCount: 3
  networkRef: "shared-vpc"
  providerConfig: "gcp-provider"
  nodePool:
    name: "default-node-pool"
    machineType: "n1-standard-1"
    diskSizeGb: 100
    diskType: "pd-standard"
    minNodeCount: 1
    maxNodeCount: 3
    autoRepair: true
    autoUpgrade: true
    labels:
      environment: "nonprod"
      team: "platform-engineering"
    taints:
      - key: "node-type"
        value: "infra"
        effect: "NO_SCHEDULE"

  # Helm Chart Deployment Config
  helm:
    enabled: true
    releaseName: "gke-cluster"
    namespace: "crossplane-system"
    repo: "https://github.com/isgo-golgo13/crossplane-argocd-gcp-drone-attack-services.git"
    chartPath: "crossplane/packages/gcp/gcp-gke"
    version: "0.1.0"
    values:
      projectId: "cxp-gcp"
      clusterName: "gke-cluster"
      region: "us-west4"
      nodeCount: 3
      networkRef: "shared-vpc"
      providerConfig: "gcp-provider"
