apiVersion: v2
name: crossplane-azure-control-plane
description: A Helm chart for setting up a Crossplane control plane for Azure with External Secrets Operator and ArgoCD.
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: argo-cd
    version: "5.51.3"
    repository: "https://argoproj.github.io/argo-helm"

  - name: external-secrets
    version: "0.9.10"
    repository: "https://charts.external-secrets.io"

  - name: crossplane
    version: "1.14.2"
    repository: "https://charts.crossplane.io/stable"

  - name: cert-manager
    version: "1.14.2"
    repository: "https://charts.jetstack.io"
