image: "gcr.io/cp-gcp-drone-svcs-project/drone-colony-dstar-gke"
spanner:
  instance: "spanner-instance"
  database: "drone_tracking"
replicaCount: 2
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"