apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
{{- range .Values.clusters }}
                - cluster: {{ .name }}
                  url: {{ .url }}
                  values: {{ .valuesFile }}
{{- end }}
          - git:
              repoURL: https://github.com/eqlgames/eql-argocd-apps
              revision: HEAD
              directories:
                - path: cluster-addons/*
  template:
    metadata:
      name: '{{`{{ cluster }}`}}-{{`{{ path.basename }}`}}'
      labels:
        env: '{{`{{ cluster }}`}}'
        type: cluster-addons
    spec:
      project: cluster-addons
      source:
        repoURL: https://github.com/eqlgames/eql-argocd-apps
        targetRevision: HEAD
        path: '{{`{{ path }}`}}'
        helm:
          valueFiles:
            - env/{{`{{ cluster }}`}}/{{`{{ values }}`}}
      destination:
        server: '{{`{{ url }}`}}'
        namespace: '{{`{{ path.basename }}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
